version: '3.1'
services:
  stats-server:
    build: stats-mvc/stats-service
    image: stat-image
    container_name: stat-container
    ports:
         - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/statsmvc
      - SPRING_DATASOURCE_USER=statsmvc
      - SPRING_DATASOURCE_PASSWORD=statsmvc

  stats-db:
    image: postgres:14-alpine
    container_name: stat-db-container
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=statsmvc
      - POSTGRES_USER=statsmvc
      - POSTGRES_PASSWORD=statsmvc
  ewm-service:
    build: main-mvc
    image: mvc-image
    container_name: mvc-container
    ports:
      - "8080:8080"
    depends_on:
      - stats-server
      - ewm-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/mainmvc
      - SPRING_DATASOURCE_USER=mainmvc
      - SPRING_DATASOURCE_PASSWORD=mainmvc
      - client.url=http://stats-server:9090

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-db-container
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=mainmvc
      - POSTGRES_USER=mainmvc
      - POSTGRES_PASSWORD=mainmvc

